# Generated by Django 5.2.13 on 2026-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("snippet", models.TextField(blank=True, default="")),
                ("source", models.CharField(max_length=255)),
                ("source_url", models.URLField(max_length=1024, unique=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("topic_tag", models.CharField(blank=True, max_length=100, null=True)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-published_at"],
            },
        ),
    ]
