# Generated by Django 5.2.13 on 2026-05-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("layoffs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS Feed"),
                            ("api", "API Endpoint"),
                            ("web", "Web Scrape"),
                            ("llm", "LLM Query"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                ("interval_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
            },
        ),
        migrations.CreateModel(
            name="ScrapedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "matched_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraped_articles",
                        to="layoffs.layoffevent",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_articles",
                        to="scraper.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraped Article",
                "verbose_name_plural": "Scraped Articles",
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("articles_found", models.PositiveIntegerField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.FloatField(default=0.0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scraper.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrape Log",
                "verbose_name_plural": "Scrape Logs",
                "ordering": ["-ran_at"],
            },
        ),
    ]
