# Generated by Django 5.2.13 on 2026-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedarticle",
            name="url",
            field=models.URLField(blank=True, default="", max_length=1024),
        ),
    ]
