# Generated by Django 5.2.13 on 2026-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LayoffEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(db_index=True, max_length=255)),
                ("headcount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("date_reported", models.DateField(db_index=True)),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.URLField(max_length=1024)),
                (
                    "source_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_ai_related", models.BooleanField(db_index=True, default=False)),
                (
                    "industry",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Layoff Event",
                "verbose_name_plural": "Layoff Events",
                "ordering": ["-date_reported"],
                "indexes": [
                    models.Index(
                        fields=["-date_reported", "is_verified"],
                        name="layoffs_lay_date_re_7a58b0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "date_reported", "headcount"),
                        name="unique_layoff_event",
                    )
                ],
            },
        ),
    ]
