# Generated by Django 5.2.13 on 2026-05-09 13:27

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    LayoffEvent = apps.get_model('layoffs', 'LayoffEvent')
    for event in LayoffEvent.objects.filter(slug=''):
        base = slugify(event.company)[:200] or 'unknown'
        base = f'{base}-{event.date_reported}'
        if event.headcount:
            base = f'{base}-{event.headcount}'
        event.slug = base
        event.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('layoffs', '0002_layoffevent_slug'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
