# Generated by Django 5.2.13 on 2026-05-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layoffs", "0003_backfill_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layoffevent",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
    ]
